import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import FavoritesProvider from "@/context/FavoritesProvider";
import NextTopLoader from "nextjs-toploader";

const PlusJakartaSans = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="mytheme">
      <body className={PlusJakartaSans.className}>
        <NextTopLoader />
        <FavoritesProvider>{children}</FavoritesProvider>
      </body>
    </html>
  );
}
